### ISSUE TITLE
代码请教

### ISSUE THREAD

**Issue by wyyhaha-rgb** [desperadoccy/async-FL#1]
您好~  我想请教一下，为什么在训练过程中训练会异常终止呢？

**Comment by desperadoccy** [comment]
可以发一下报错截图吗，或者加个联系方式交流，QQ：527707607



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月14日(周四) 晚上9:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [desperadoccy/async-FL] 代码请教 (Issue #1)




 
您好~  我想请教一下，为什么在训练过程中训练会异常终止呢？

**Comment by desperadoccy** [comment]
最近代码更新比较快，然后文档和json更新有点滞后了，暂时发现一个问题是同步文件中忘记更新loss字段了。updater现要指定loss，以获取test_loss值
