### ISSUE TITLE
Question about Async-FL

### ISSUE THREAD

**Issue by Ting-You** [desperadoccy/async-FL#6]
Hi,
I am writing to ask about a function you provide on GitHub.
Is the file in “async-FL/src/update/StepAsyncAvg.py” the implementation of “KAFL: Achieving High Training Efficiency for Fast-K Asynchronous Federated Learning” (ICDCS)?

Thank you.

**Comment by desperadoccy** [comment]
yes, it is. This file contains the algorithm for the server update part. Please refer to the configuration file `config/MSTEPAsync-config.json` for the complete composition of the algorithm.

**Comment by desperadoccy** [comment]
The workload has been quite heavy lately, and the README document is quite outdated. If there are any parts that you don't understand, feel free to discuss with me🤝.

**Comment by Ting-You** [comment]
OK!
Thanks for your reply.
