### ISSUE TITLE
Question about FedAT

### ISSUE THREAD

**Issue by mmkdlin** [desperadoccy/async-FL#7]
![fedat loss](https://github.com/desperadoccy/async-FL/assets/40222893/3a7ae2e7-6144-430c-aa92-5c01cefe55a4)
![fedat acc](https://github.com/desperadoccy/async-FL/assets/40222893/c687c831-e9e4-4a06-a588-08d7de1bf1b2)
我在进行fedat实验时遇到以下问题:
蓝色线为config未改动时的情况，震荡非常大而且准确度并不高请问这是正常的吗?
红色线为将iid设置为true时的状况，想请问为何会遇到这样的问题?
I have the following problem while running fedat experiment:
The blue line is the situation when the config has not been changed. The vibration is very large and the accuracy is not high. Is this normal?
The red line is the situation when iid is set to true. I would like to ask why you encounter such a problem?

**Comment by desperadoccy** [comment]
我复现出来也大致是这样的情况，我认为是不正常的。这是我早期实现的算法之一，可能存在论文理解有误的情况，我最近正在迭代3.0版本，迭代完成后将研究下这个问题。欢迎添加联系方法深入交流

**Comment by desperadoccy** [comment]
该bug已经排查完成，fedat根据每簇的迭代次数进行加权，原实现所有的迭代次数初始化为0，导致大部分更新全部被忽略，更改fedat两处代码即可修正。
该修改会随3.0更新同步上传，如果着急需要，烦请自行修改。
整体代码如下：
```python

    def update_server_weights(self, epoch, update_list):
        group_num = len(update_list)
        epoch_list = self.updater_thread.get_epoch_list()
        updated_parameters = {}
        for key, var in update_list[0]["weights"].items():
            updated_parameters[key] = update_list[0]["weights"][key] * (epoch_list[group_num - 1 - 0] + 1) / epoch
        for i in range(len(update_list) - 1):
            update_dict = update_list[i + 1]
            client_weights = update_dict["weights"]
            for key, var in client_weights.items():
                updated_parameters[key] += client_weights[key] * (epoch_list[group_num - 1 - i] + 1) / epoch
        # 下发给客户端的权重
        self.updater_thread.global_var['scheduler'].server_weights = updated_parameters
        return updated_parameters
```

**Comment by mmkdlin** [comment]
不好意思，想再请问一下倒数第三行的
updated_parameters[key] += client_weights[key] * (epoch_list[group_num - 1 - 0] + 1) / epoch
是否应该为
updated_parameters[key] += client_weights[key] * (epoch_list[group_num - 1 - i] + 1) / epoch

另外还想请问ACC会持续下降的原因是什么?
从FEDAT论文中的结论应该会比FEDASYNC更好但实验中看起来还有一段差距 想了解一下原因

![W B Chart 2023_6_2 下午1_08_33](https://github.com/desperadoccy/async-FL/assets/40222893/213ac317-afb0-487b-a257-dc39c55c5a94)

**Comment by desperadoccy** [comment]
噢，抱歉是应该`group_num - 1 - i`
acc下降大概率过拟合了
至于为什么不如FedAsync，可能50个客户端共分数据集，数据量已经比较小，可以降低客户端数量试试。（他的实验不开源，不清楚他的实验配置，你可以试试调整参数可能会优化acc）

**Comment by desperadoccy** [comment]
我还是重新说明一下，原算法也是没有漏洞了，当初实现的时候，考虑着所有的epoch都会自动增长到1之后，他就会自然收敛。他原文也没有特别提起这边应该怎么设计，所以原先是这么实现的。之前为什么不收敛是因为最后一组延迟太高，之前几十个迭代他都没有参与到聚合。

**Comment by desperadoccy** [comment]
所以考虑再三，我决定还是沿用之前的设定
